-- =============================================================================
-- Mani Library — ORGANIZED SCHEMA v2 (greenfield)
-- =============================================================================
-- Run in an EMPTY Supabase project (SQL Editor) after `auth` exists.
--
-- DESIGN GOALS (per product spec)
--   • One clear “core” set: profiles, memberships, payments, verification.
--   • “Active *” are VIEWS only (no duplicate membership/payment tables).
--   • KYC files: normalized table `verification_documents` (not JSON blobs).
--   • Device vendor APIs: ONE ingest table `device_api_records` (+ thin map).
--   • CSV / manual member onboarding: `member_manual_import` (staging).
--   • `device_user_id`: identity 1111–9999, immutable on profile; maps to eTime
--     `empcode` via `etime_empcode_map` for the face device.
--   • Sensitive columns: `admin_internal_note_cipher`, optional `profile_pii_cipher`
--     using `encrypt_note` / `decrypt_note` (pgcrypto; passphrase via session or Vault).
--   • RLS on every base table; service_role bypasses RLS for server jobs.
--
-- TABLE COUNT (physical base tables): 12
--   1 profiles
--   2 verification
--   3 verification_documents
--   4 memberships
--   5 payments
--   6 membership_events
--   7 attendance_days
--   8 library_export_audit
--   9 device_api_records          ← replaces etime_punch_raw + etime_attendance_daily
--  10 etime_empcode_map           ← empcode (0001) ↔ device_user_id
--  11 member_manual_import        ← CSV / manual rows before Auth user exists
--  12 device_api_sync_state       ← LastRecord / incremental cursors per empcode
--
-- VIEWS (not counted as tables): 5
--   device_lookup, active_profiles, active_memberships, active_payments,
--   active_verification_documents
--
-- BREAKING vs `new-database-schema-rls-encryption.sql`:
--   • App must read/write `verification_documents` instead of `verification.documents` jsonb.
--   • App must read/write `device_api_records` instead of `etime_punch_raw` / `etime_attendance_daily`.
-- =============================================================================

create extension if not exists pgcrypto;
create extension if not exists btree_gist;

-- ---------------------------------------------------------------------------
-- Encryption helpers (set `app.library_passphrase` in session for encrypt;
-- production: wrap with Vault — see old schema comments.)
-- ---------------------------------------------------------------------------
create or replace function public.encrypt_note(p_plain text)
returns bytea
language sql
stable
as $$
  select case
    when p_plain is null then null::bytea
    when nullif(trim(current_setting('app.library_passphrase', true)), '') is null then null::bytea
    else pgp_sym_encrypt(p_plain, current_setting('app.library_passphrase'), 'cipher-algo=aes256')
  end;
$$;

create or replace function public.decrypt_note(p_secret bytea)
returns text
language sql
stable
as $$
  select case
    when p_secret is null then null::text
    when nullif(trim(current_setting('app.library_passphrase', true)), '') is null then null::text
    else pgp_sym_decrypt(p_secret, current_setting('app.library_passphrase'))::text
  end;
$$;

revoke all on function public.encrypt_note(text) from public;
revoke all on function public.decrypt_note(bytea) from public;
grant execute on function public.encrypt_note(text) to service_role;
grant execute on function public.decrypt_note(bytea) to service_role;

-- ---------------------------------------------------------------------------
-- 1 profiles
-- ---------------------------------------------------------------------------
create table public.profiles (
  user_id            uuid primary key references auth.users (id) on delete cascade,
  device_user_id     int generated by default as identity (
    start with 1111 increment by 1 minvalue 1111 maxvalue 9999 no cycle
  ) not null unique,
  full_name          text not null,
  phone              text,
  email              text,
  avatar_url         text,
  is_admin           boolean not null default false,
  is_superadmin      boolean not null default false,
  is_verified        boolean not null default false,
  is_active          boolean not null default true,
  profile_extras     jsonb not null default '{}'::jsonb,
  profile_pii_cipher bytea,
  deleted_at         timestamptz,
  deleted_by         uuid references auth.users (id) on delete set null,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  constraint profiles_device_user_id_range check (device_user_id >= 0 and device_user_id <= 9999)
);

create index profiles_device_user_id_idx on public.profiles (device_user_id);
create index profiles_active_idx on public.profiles (user_id) where deleted_at is null;

-- Role helpers (SECURITY DEFINER)
create or replace function public.is_library_admin()
returns boolean language sql stable security definer set search_path = public set row_security = off as $$
  select coalesce((select p.is_admin from public.profiles p where p.user_id = auth.uid() and p.deleted_at is null and p.is_active), false);
$$;

create or replace function public.is_library_superadmin()
returns boolean language sql stable security definer set search_path = public set row_security = off as $$
  select coalesce((select p.is_superadmin from public.profiles p where p.user_id = auth.uid() and p.deleted_at is null and p.is_active), false);
$$;

revoke all on function public.is_library_admin() from public;
grant execute on function public.is_library_admin() to authenticated, service_role;
revoke all on function public.is_library_superadmin() from public;
grant execute on function public.is_library_superadmin() to authenticated, service_role;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (user_id, full_name, phone, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', 'Member'),
    coalesce(new.raw_user_meta_data->>'phone', new.phone),
    new.email
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.profiles_lock_device_user_id()
returns trigger language plpgsql as $$
begin
  if new.device_user_id is distinct from old.device_user_id then
    raise exception 'device_user_id is immutable (user_id=%)', old.user_id;
  end if;
  new.updated_at := now();
  return new;
end;
$$;

create trigger trg_profiles_lock_device_user_id before update on public.profiles
  for each row execute function public.profiles_lock_device_user_id();

create or replace function public.profiles_prevent_role_self_promotion()
returns trigger language plpgsql security definer set search_path = public set row_security = off as $$
declare
  caller_is_superadmin boolean;
  role_change boolean := (new.is_admin is distinct from old.is_admin)
    or (new.is_superadmin is distinct from old.is_superadmin);
  sess text := lower(session_user::text);
begin
  if tg_op <> 'UPDATE' then return new; end if;
  if not role_change then
    return new;
  end if;

  -- SQL Editor / psql as database owner (session_user is stable inside SECURITY DEFINER).
  if sess in ('postgres', 'supabase_admin') then
    return new;
  end if;

  if auth.uid() is null then
    return new;
  end if;

  if new.user_id = auth.uid() then
    raise exception 'cannot change your own role flags — ask another superadmin';
  end if;

  select p.is_superadmin into caller_is_superadmin
  from public.profiles p where p.user_id = auth.uid() and p.deleted_at is null;
  if not coalesce(caller_is_superadmin, false) then
    raise exception 'only a superadmin can change role flags';
  end if;
  return new;
end;
$$;

create trigger trg_profiles_prevent_role_self_promotion before update on public.profiles
  for each row execute function public.profiles_prevent_role_self_promotion();

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$ begin new.updated_at := now(); return new; end; $$;

-- ---------------------------------------------------------------------------
-- 2 verification  (workflow only — files live in verification_documents)
-- ---------------------------------------------------------------------------
create table public.verification (
  id                         uuid primary key default gen_random_uuid(),
  user_id                    uuid not null references auth.users (id) on delete cascade,
  status                     text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected', 'resubmit')),
  submitted_at               timestamptz not null default now(),
  reviewed_at                timestamptz,
  reviewed_by                uuid references auth.users (id),
  admin_internal_note_cipher bytea,
  student_message            text,
  resubmit_count             int not null default 0,
  deleted_at                 timestamptz,
  deleted_by                 uuid references auth.users (id) on delete set null,
  created_at                 timestamptz not null default now(),
  updated_at                 timestamptz not null default now()
);

create unique index verification_one_pending_per_user
  on public.verification (user_id) where status = 'pending' and deleted_at is null;

create index verification_user_idx on public.verification (user_id);

create or replace function public.sync_profile_is_verified_from_verification()
returns trigger language plpgsql security definer set search_path = public set row_security = off as $$
begin
  if tg_op = 'UPDATE' and new.status is distinct from old.status then
    if new.status = 'approved' then
      update public.profiles set is_verified = true, updated_at = now() where user_id = new.user_id;
    elsif new.status in ('rejected', 'resubmit', 'pending') then
      update public.profiles set is_verified = false, updated_at = now() where user_id = new.user_id;
    end if;
  end if;
  return new;
end;
$$;

create trigger trg_sync_profile_is_verified after update on public.verification
  for each row execute function public.sync_profile_is_verified_from_verification();

create trigger trg_verification_updated before update on public.verification
  for each row execute function public.touch_updated_at();

create or replace function public.verification_guard_member_updates()
returns trigger language plpgsql security definer set search_path = public set row_security = off as $$
begin
  if tg_op = 'UPDATE' and new.user_id = auth.uid()
     and not coalesce((select p.is_admin from public.profiles p where p.user_id = auth.uid() and p.deleted_at is null), false)
     and not coalesce((select p.is_superadmin from public.profiles p where p.user_id = auth.uid() and p.deleted_at is null), false) then
    if new.status is distinct from old.status
       or new.reviewed_at is distinct from old.reviewed_at
       or new.reviewed_by is distinct from old.reviewed_by
       or new.admin_internal_note_cipher is distinct from old.admin_internal_note_cipher
       or new.deleted_at is distinct from old.deleted_at
       or new.deleted_by is distinct from old.deleted_by
       or new.submitted_at is distinct from old.submitted_at then
      raise exception 'members may only update student_message or resubmit_count while pending (use verification_documents for files)';
    end if;
  end if;
  return new;
end;
$$;

create trigger trg_verification_guard_member before update on public.verification
  for each row execute function public.verification_guard_member_updates();

-- ---------------------------------------------------------------------------
-- 3 verification_documents
-- ---------------------------------------------------------------------------
create table public.verification_documents (
  id               uuid primary key default gen_random_uuid(),
  verification_id  uuid not null references public.verification (id) on delete cascade,
  user_id          uuid not null references auth.users (id) on delete cascade,
  doc_type         text not null check (doc_type in ('aadhaar_front', 'aadhaar_back', 'student_id')),
  phase            text not null check (phase in ('checkout_pending', 'submitted')),
  storage_bucket   text not null,
  storage_path     text not null,
  content_type     text not null,
  deleted_at       timestamptz,
  deleted_by       uuid references auth.users (id) on delete set null,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create unique index verification_documents_one_per_slot
  on public.verification_documents (verification_id, doc_type, phase)
  where deleted_at is null;

create index verification_documents_user_idx on public.verification_documents (user_id);

create trigger trg_verification_documents_updated before update on public.verification_documents
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- 4 memberships  /  5 payments
-- ---------------------------------------------------------------------------
create table public.memberships (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references auth.users (id) on delete cascade,
  plan_kind       text not null check (plan_kind in ('short_term', 'long_term')),
  status          text not null default 'pending_payment'
    check (status in ('pending_payment', 'active', 'expired', 'cancelled')),
  seat_number     text,
  starts_at       timestamptz,
  ends_at         timestamptz,
  valid_from      date,
  valid_until     date,
  payment_id      uuid,
  notes           text,
  deleted_at      timestamptz,
  deleted_by      uuid references auth.users (id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  constraint memberships_short_term_window check (
    plan_kind <> 'short_term' or (starts_at is not null and ends_at is not null and ends_at > starts_at)
  ),
  constraint memberships_long_term_window check (
    plan_kind <> 'long_term' or (valid_from is not null and valid_until is not null and valid_until >= valid_from)
  ),
  constraint memberships_seat_no_overlap_short_term exclude using gist (
    seat_number with =,
    tstzrange(starts_at, ends_at, '[)') with &&
  ) where (status = 'active' and plan_kind = 'short_term' and seat_number is not null and deleted_at is null),
  constraint memberships_seat_no_overlap_long_term exclude using gist (
    seat_number with =,
    daterange(valid_from, (valid_until + 1), '[)') with &&
  ) where (status = 'active' and plan_kind = 'long_term' and seat_number is not null and deleted_at is null)
);

create table public.payments (
  id                    uuid primary key default gen_random_uuid(),
  user_id               uuid not null references auth.users (id) on delete cascade,
  membership_id         uuid references public.memberships (id) on delete set null,
  amount_rupees         bigint not null check (amount_rupees >= 0),
  currency              text not null default 'INR',
  provider              text,
  provider_payment_id   text,
  status                text not null default 'pending'
    check (status in ('pending', 'paid', 'failed', 'refunded')),
  metadata              jsonb not null default '{}'::jsonb,
  idempotency_key       text,
  deleted_at            timestamptz,
  deleted_by            uuid references auth.users (id) on delete set null,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

create unique index payments_idempotency_pending_idx
  on public.payments (idempotency_key) where idempotency_key is not null and status = 'pending' and deleted_at is null;

create index memberships_user_idx on public.memberships (user_id);
create index memberships_user_status_idx on public.memberships (user_id, status) where deleted_at is null;
create index memberships_payment_idx on public.memberships (payment_id);

create index payments_user_idx on public.payments (user_id);
create trigger trg_payments_updated before update on public.payments for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- 6 membership_events
-- ---------------------------------------------------------------------------
create table public.membership_events (
  id              uuid primary key default gen_random_uuid(),
  membership_id   uuid not null,
  user_id         uuid references auth.users (id) on delete set null,
  event_type      text not null
    check (event_type in (
      'created', 'activated', 'expired', 'cancelled', 'renewed',
      'seat_assigned', 'seat_changed', 'payment_linked', 'soft_deleted', 'hard_deleted', 'updated'
    )),
  old_status      text,
  new_status      text,
  changed_by      uuid references auth.users (id) on delete set null,
  changed_by_role text check (changed_by_role is null or changed_by_role in ('member', 'admin', 'superadmin', 'system')),
  note            text,
  created_at      timestamptz not null default now()
);

create index membership_events_membership_idx on public.membership_events (membership_id);

create or replace function public.memberships_log_event()
returns trigger language plpgsql security definer set search_path = public set row_security = off as $$
declare
  uid uuid := auth.uid();
  r text := case
  when coalesce((select p.is_superadmin from public.profiles p where p.user_id = uid and p.deleted_at is null), false) then 'superadmin'
  when coalesce((select p.is_admin from public.profiles p where p.user_id = uid and p.deleted_at is null), false) then 'admin'
  when uid is not null then 'member' else 'system' end;
begin
  if tg_op = 'INSERT' then
    insert into public.membership_events (membership_id, user_id, event_type, new_status, changed_by, changed_by_role)
    values (new.id, new.user_id, 'created', new.status, uid, r);
    return new;
  end if;
  if tg_op = 'UPDATE' then
    if new.deleted_at is not null and old.deleted_at is null then
      insert into public.membership_events (membership_id, user_id, event_type, old_status, new_status, changed_by, changed_by_role)
      values (new.id, new.user_id, 'soft_deleted', old.status, new.status, uid, r);
    elsif new.status is distinct from old.status then
      insert into public.membership_events (membership_id, user_id, event_type, old_status, new_status, changed_by, changed_by_role)
      values (new.id, new.user_id, 'updated', old.status, new.status, uid, r);
    end if;
  end if;
  return new;
end;
$$;

create trigger trg_memberships_log_event_aiu after insert or update on public.memberships
  for each row execute function public.memberships_log_event();

create or replace function public.memberships_log_event_delete()
returns trigger language plpgsql security definer set search_path = public set row_security = off as $$
declare
  uid uuid := auth.uid();
  r text := case
  when coalesce((select p.is_superadmin from public.profiles p where p.user_id = uid and p.deleted_at is null), false) then 'superadmin'
  when coalesce((select p.is_admin from public.profiles p where p.user_id = uid and p.deleted_at is null), false) then 'admin'
  when uid is not null then 'member' else 'system' end;
begin
  insert into public.membership_events (membership_id, user_id, event_type, old_status, changed_by, changed_by_role)
  values (old.id, old.user_id, 'hard_deleted', old.status, uid, r);
  return old;
end;
$$;

create trigger trg_memberships_log_event_del before delete on public.memberships
  for each row execute function public.memberships_log_event_delete();

-- ---------------------------------------------------------------------------
-- 7 attendance_days  /  8 library_export_audit
-- ---------------------------------------------------------------------------
create table public.attendance_days (
  id                          uuid primary key default gen_random_uuid(),
  library_day_ymd             date not null,
  device_from_dmy             text not null,
  device_to_dmy               text not null,
  source                      text not null,
  items                       jsonb not null,
  member_rows                 jsonb not null default '[]'::jsonb,
  skipped_unregistered        int not null default 0,
  archived_at                 timestamptz not null default now(),
  processed_by_user_id        uuid references auth.users (id) on delete set null,
  processed_by_device_user_id int references public.profiles (device_user_id) on update cascade on delete set null,
  processed_by_full_name      text,
  deleted_at                  timestamptz,
  deleted_by                  uuid references auth.users (id) on delete set null,
  unique (library_day_ymd)
);

create table public.library_export_audit (
  id                 uuid primary key default gen_random_uuid(),
  device_user_id     int references public.profiles (device_user_id) on update cascade on delete cascade,
  full_name          text,
  created_at         timestamptz not null default now(),
  created_by         uuid references auth.users (id) on delete set null,
  from_ymd           date not null,
  to_ymd             date not null,
  directory_rows     int not null default 0,
  membership_rows    int not null default 0,
  payment_rows       int not null default 0,
  attendance_rows    int not null default 0,
  attendance_capped  boolean not null default false,
  workbook_bytes     bigint not null default 0,
  deleted_at         timestamptz,
  deleted_by         uuid references auth.users (id) on delete set null
);

-- ---------------------------------------------------------------------------
-- 9 device_api_records  (MCID punches + IN/OUT daily rows + optional last-punch payload)
-- ---------------------------------------------------------------------------
create table public.device_api_records (
  id               bigserial primary key,
  device_user_id   int not null references public.profiles (device_user_id) on update cascade on delete cascade,
  empcode          text not null,
  source_api       text not null check (source_api in ('DownloadPunchDataMCID', 'DownloadInOutPunchData', 'DownloadLastPunchData', 'other')),
  record_kind      text not null check (record_kind in ('punch', 'daily_summary', 'incremental_meta')),
  event_at         timestamptz not null,
  work_date        date,
  mcid             text not null default '',
  raw              jsonb not null,
  fetched_at       timestamptz not null default now(),
  deleted_at       timestamptz,
  deleted_by       uuid references auth.users (id) on delete set null
);

create unique index device_api_records_dedupe_punch
  on public.device_api_records (device_user_id, event_at, mcid, record_kind)
  where record_kind = 'punch' and deleted_at is null;

create unique index device_api_records_dedupe_daily
  on public.device_api_records (device_user_id, work_date, record_kind)
  where record_kind = 'daily_summary' and deleted_at is null and work_date is not null;

create index device_api_records_device_time_idx on public.device_api_records (device_user_id, event_at desc);

-- ---------------------------------------------------------------------------
-- 10 etime_empcode_map
-- ---------------------------------------------------------------------------
create table public.etime_empcode_map (
  empcode          text primary key,
  device_user_id   int not null references public.profiles (device_user_id) on update cascade on delete cascade,
  notes            text,
  created_at       timestamptz not null default now(),
  deleted_at       timestamptz,
  deleted_by       uuid references auth.users (id) on delete set null
);

-- ---------------------------------------------------------------------------
-- 11 member_manual_import  (CSV staging — no Auth user until “apply” flow)
-- ---------------------------------------------------------------------------
create table public.member_manual_import (
  id               uuid primary key default gen_random_uuid(),
  import_batch_id  uuid not null,
  row_number       int not null,
  full_name        text,
  phone            text,
  email            text,
  suggested_empcode text,
  notes            text,
  raw_row          jsonb not null default '{}'::jsonb,
  status           text not null default 'pending' check (status in ('pending', 'applied', 'skipped', 'error')),
  error_message    text,
  applied_user_id  uuid references auth.users (id) on delete set null,
  created_by       uuid references auth.users (id) on delete set null,
  created_at       timestamptz not null default now(),
  unique (import_batch_id, row_number)
);

create index member_manual_import_batch_idx on public.member_manual_import (import_batch_id);

-- ---------------------------------------------------------------------------
-- 12 device_api_sync_state  (LastRecord / incremental)
-- ---------------------------------------------------------------------------
create table public.device_api_sync_state (
  empcode        text primary key,
  last_cursor    text not null default '',
  updated_at     timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- VIEWS
-- ---------------------------------------------------------------------------
create or replace view public.device_lookup as
  select device_user_id, user_id, full_name from public.profiles where deleted_at is null;

create or replace view public.active_profiles as
  select * from public.profiles where deleted_at is null;

create or replace view public.active_memberships as
  select * from public.memberships where deleted_at is null;

create or replace view public.active_payments as
  select * from public.payments where deleted_at is null;

create or replace view public.active_verification_documents as
  select vd.*
  from public.verification_documents vd
  inner join public.verification v on v.id = vd.verification_id
  where vd.deleted_at is null and v.deleted_at is null;

-- ---------------------------------------------------------------------------
-- RLS enable + policies (summary: same matrix as v1; new tables wired)
-- ---------------------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.verification enable row level security;
alter table public.verification_documents enable row level security;
alter table public.memberships enable row level security;
alter table public.payments enable row level security;
alter table public.membership_events enable row level security;
alter table public.attendance_days enable row level security;
alter table public.library_export_audit enable row level security;
alter table public.device_api_records enable row level security;
alter table public.etime_empcode_map enable row level security;
alter table public.member_manual_import enable row level security;
alter table public.device_api_sync_state enable row level security;

-- profiles
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select using (
  (user_id = auth.uid() or public.is_library_admin() or public.is_library_superadmin())
  and (deleted_at is null or public.is_library_superadmin())
);
drop policy if exists profiles_insert_none on public.profiles;
create policy profiles_insert_none on public.profiles for insert with check (false);
drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles for update
  using ((user_id = auth.uid() or public.is_library_admin() or public.is_library_superadmin()) and (deleted_at is null or public.is_library_superadmin()))
  with check ((user_id = auth.uid() or public.is_library_admin() or public.is_library_superadmin()) and (deleted_at is null or public.is_library_superadmin()));
drop policy if exists profiles_delete_super on public.profiles;
create policy profiles_delete_super on public.profiles for delete using (public.is_library_superadmin());

-- verification
drop policy if exists verification_select on public.verification;
create policy verification_select on public.verification for select using (
  (user_id = auth.uid() or public.is_library_admin() or public.is_library_superadmin())
  and (deleted_at is null or public.is_library_superadmin())
);
drop policy if exists verification_insert on public.verification;
create policy verification_insert on public.verification for insert with check (user_id = auth.uid() and status = 'pending' and deleted_at is null);
drop policy if exists verification_update on public.verification;
create policy verification_update on public.verification for update
  using ((user_id = auth.uid() or public.is_library_admin() or public.is_library_superadmin()) and (deleted_at is null or public.is_library_superadmin()))
  with check ((user_id = auth.uid() or public.is_library_admin() or public.is_library_superadmin()) and (deleted_at is null or public.is_library_superadmin()));
drop policy if exists verification_delete_super on public.verification;
create policy verification_delete_super on public.verification for delete using (public.is_library_superadmin());

-- verification_documents
drop policy if exists vd_select on public.verification_documents;
create policy vd_select on public.verification_documents for select using (
  (user_id = auth.uid() or public.is_library_admin() or public.is_library_superadmin())
  and (deleted_at is null or public.is_library_superadmin())
);
drop policy if exists vd_insert on public.verification_documents;
create policy vd_insert on public.verification_documents for insert
  with check (
    user_id = auth.uid()
    and deleted_at is null
    and exists (select 1 from public.verification v where v.id = verification_id and v.user_id = auth.uid() and v.deleted_at is null)
  );
drop policy if exists vd_update on public.verification_documents;
create policy vd_update on public.verification_documents for update
  using ((user_id = auth.uid() or public.is_library_admin() or public.is_library_superadmin()) and (deleted_at is null or public.is_library_superadmin()))
  with check ((user_id = auth.uid() or public.is_library_admin() or public.is_library_superadmin()) and (deleted_at is null or public.is_library_superadmin()));
drop policy if exists vd_delete_super on public.verification_documents;
create policy vd_delete_super on public.verification_documents for delete using (public.is_library_superadmin());

-- memberships / payments / membership_events — same as v1
drop policy if exists memberships_select on public.memberships;
create policy memberships_select on public.memberships for select using (
  (user_id = auth.uid() or public.is_library_admin() or public.is_library_superadmin()) and (deleted_at is null or public.is_library_superadmin())
);
drop policy if exists memberships_insert on public.memberships;
create policy memberships_insert on public.memberships for insert with check (user_id = auth.uid() and deleted_at is null);
drop policy if exists memberships_update on public.memberships;
create policy memberships_update on public.memberships for update
  using ((user_id = auth.uid() or public.is_library_admin() or public.is_library_superadmin()) and (deleted_at is null or public.is_library_superadmin()))
  with check (user_id = auth.uid() or public.is_library_admin() or public.is_library_superadmin());
drop policy if exists memberships_delete_super on public.memberships;
create policy memberships_delete_super on public.memberships for delete using (public.is_library_superadmin());

drop policy if exists payments_select on public.payments;
create policy payments_select on public.payments for select using (
  (user_id = auth.uid() or public.is_library_admin() or public.is_library_superadmin()) and (deleted_at is null or public.is_library_superadmin())
);
drop policy if exists payments_insert on public.payments;
create policy payments_insert on public.payments for insert with check (user_id = auth.uid() and deleted_at is null);
drop policy if exists payments_update on public.payments;
create policy payments_update on public.payments for update
  using ((user_id = auth.uid() or public.is_library_admin() or public.is_library_superadmin()) and (deleted_at is null or public.is_library_superadmin()))
  with check (user_id = auth.uid() or public.is_library_admin() or public.is_library_superadmin());
drop policy if exists payments_delete_super on public.payments;
create policy payments_delete_super on public.payments for delete using (public.is_library_superadmin());

drop policy if exists membership_events_select on public.membership_events;
create policy membership_events_select on public.membership_events for select
  using (user_id = auth.uid() or public.is_library_admin() or public.is_library_superadmin());
drop policy if exists membership_events_insert on public.membership_events;
create policy membership_events_insert on public.membership_events for insert
  with check (public.is_library_admin() or public.is_library_superadmin());

-- attendance_days / library_export_audit
drop policy if exists attendance_days_select on public.attendance_days;
create policy attendance_days_select on public.attendance_days for select using (
  (public.is_library_admin() or public.is_library_superadmin()) and (deleted_at is null or public.is_library_superadmin())
);
drop policy if exists attendance_days_insert on public.attendance_days;
create policy attendance_days_insert on public.attendance_days for insert with check (public.is_library_admin() or public.is_library_superadmin());
drop policy if exists attendance_days_update on public.attendance_days;
create policy attendance_days_update on public.attendance_days for update
  using (public.is_library_admin() or public.is_library_superadmin())
  with check (public.is_library_admin() or public.is_library_superadmin());
drop policy if exists attendance_days_delete_super on public.attendance_days;
create policy attendance_days_delete_super on public.attendance_days for delete using (public.is_library_superadmin());

drop policy if exists library_export_audit_select on public.library_export_audit;
create policy library_export_audit_select on public.library_export_audit for select using (
  (public.is_library_admin() or public.is_library_superadmin()) and (deleted_at is null or public.is_library_superadmin())
);
drop policy if exists library_export_audit_insert_service on public.library_export_audit;
create policy library_export_audit_insert_service on public.library_export_audit for insert with check (false);

-- device_api_records (same access pattern as old eTime tables)
drop policy if exists device_api_select on public.device_api_records;
create policy device_api_select on public.device_api_records for select to authenticated using (
  (
    device_user_id = (select p.device_user_id from public.profiles p where p.user_id = auth.uid() and p.deleted_at is null)
    or public.is_library_admin() or public.is_library_superadmin()
  ) and (deleted_at is null or public.is_library_superadmin())
);
drop policy if exists device_api_insert on public.device_api_records;
create policy device_api_insert on public.device_api_records for insert to authenticated
  with check (public.is_library_admin() or public.is_library_superadmin());
drop policy if exists device_api_update on public.device_api_records;
create policy device_api_update on public.device_api_records for update to authenticated
  using (public.is_library_admin() or public.is_library_superadmin())
  with check (public.is_library_admin() or public.is_library_superadmin());
drop policy if exists device_api_delete_super on public.device_api_records;
create policy device_api_delete_super on public.device_api_records for delete to authenticated using (public.is_library_superadmin());

-- etime_empcode_map
drop policy if exists etime_map_select on public.etime_empcode_map;
create policy etime_map_select on public.etime_empcode_map for select to authenticated using (
  (
    device_user_id = (select p.device_user_id from public.profiles p where p.user_id = auth.uid() and p.deleted_at is null)
    or public.is_library_admin() or public.is_library_superadmin()
  ) and (deleted_at is null or public.is_library_superadmin())
);
drop policy if exists etime_map_insert on public.etime_empcode_map;
create policy etime_map_insert on public.etime_empcode_map for insert to authenticated
  with check (public.is_library_admin() or public.is_library_superadmin());
drop policy if exists etime_map_update on public.etime_empcode_map;
create policy etime_map_update on public.etime_empcode_map for update to authenticated
  using (public.is_library_admin() or public.is_library_superadmin())
  with check (public.is_library_admin() or public.is_library_superadmin());
drop policy if exists etime_map_delete_super on public.etime_empcode_map;
create policy etime_map_delete_super on public.etime_empcode_map for delete to authenticated using (public.is_library_superadmin());

-- member_manual_import — staff only
drop policy if exists mmi_select on public.member_manual_import;
create policy mmi_select on public.member_manual_import for select using (public.is_library_admin() or public.is_library_superadmin());
drop policy if exists mmi_insert on public.member_manual_import;
create policy mmi_insert on public.member_manual_import for insert with check (public.is_library_admin() or public.is_library_superadmin());
drop policy if exists mmi_update on public.member_manual_import;
create policy mmi_update on public.member_manual_import for update
  using (public.is_library_admin() or public.is_library_superadmin())
  with check (public.is_library_admin() or public.is_library_superadmin());
drop policy if exists mmi_delete on public.member_manual_import;
create policy mmi_delete on public.member_manual_import for delete using (public.is_library_superadmin());

-- device_api_sync_state — staff only
drop policy if exists dass_select on public.device_api_sync_state;
create policy dass_select on public.device_api_sync_state for select using (public.is_library_admin() or public.is_library_superadmin());
drop policy if exists dass_insert on public.device_api_sync_state;
create policy dass_insert on public.device_api_sync_state for insert
  with check (public.is_library_admin() or public.is_library_superadmin());
drop policy if exists dass_update on public.device_api_sync_state;
create policy dass_update on public.device_api_sync_state for update
  using (public.is_library_admin() or public.is_library_superadmin())
  with check (public.is_library_admin() or public.is_library_superadmin());
drop policy if exists dass_delete on public.device_api_sync_state;
create policy dass_delete on public.device_api_sync_state for delete using (public.is_library_superadmin());

-- ---------------------------------------------------------------------------
-- Grants
-- ---------------------------------------------------------------------------
revoke all on all tables in schema public from anon;
revoke all on all tables in schema public from authenticated;
grant usage on schema public to anon, authenticated, service_role;

grant select, update on public.profiles to authenticated;
grant select, insert, update, delete on public.verification to authenticated;
grant select, insert, update, delete on public.verification_documents to authenticated;
grant select, insert, update, delete on public.memberships to authenticated;
grant select, insert, update, delete on public.payments to authenticated;
grant select, insert on public.membership_events to authenticated;
grant select, insert, update, delete on public.attendance_days to authenticated;
grant select on public.library_export_audit to authenticated;
grant select, insert, update, delete on public.device_api_records to authenticated;
grant select, insert, update, delete on public.etime_empcode_map to authenticated;
grant select, insert, update, delete on public.member_manual_import to authenticated;
grant select, insert, update, delete on public.device_api_sync_state to authenticated;

revoke insert, update, delete on public.library_export_audit from authenticated;
grant select, insert, update, delete on public.library_export_audit to service_role;
grant all on all tables in schema public to service_role;

grant select on public.device_lookup to authenticated;
grant select on public.active_profiles to authenticated;
grant select on public.active_memberships to authenticated;
grant select on public.active_payments to authenticated;
grant select on public.active_verification_documents to authenticated;

-- =============================================================================
-- FOOTER — bootstrap superadmin (SQL Editor; disable role trigger if needed)
-- =============================================================================
-- alter table public.profiles disable trigger trg_profiles_prevent_role_self_promotion;
-- update public.profiles set is_superadmin = true, is_admin = true where user_id = '…'::uuid;
-- alter table public.profiles enable trigger trg_profiles_prevent_role_self_promotion;
-- =============================================================================
