-- =============================================================================
-- Core tables + field-length limits (no views).
-- =============================================================================
-- Use as a greenfield template: profiles, verification, verification_documents,
-- memberships, payments, testimonials.
--
-- Layering reminder:
--   • DB limits = safety net against oversized rows / buggy servers.
--   • Backend must still validate before insert (reuse FIELD_LIMITS in app code).
--   • Frontend maxLength is UX only, not security.
--
-- Naming mirrors manilibrary/src/lib/security/field-limits.ts where applicable.
-- =============================================================================

begin;

create extension if not exists "pgcrypto";

-- Size caps (characters unless noted).
-- tweak for your product; keep backend constants in sync.
-- -----------------------------------------------------------------------------
-- Limits reference (characters):
--   name 2–100, email ≤254, phone ≤40, short line ≤200,
--   admin/reviewer message ≤2000, seat/plan/status short strings,
--   storage path ≤1024, URL ≤2048,
--   membership notes ≤4000,
--   testimonial title ≤200, body 10–8000,
--   jsonb serialised representation ≤24 KiB (approximate octet guard below)

create table public.profiles (
  user_id            uuid primary key references auth.users (id) on delete cascade,

  external_member_no bigint generated by default as identity,

  full_name          varchar(100) not null
    constraint profiles_full_name_trim_len_check
      check (char_length(trim(full_name)) >= 2 and char_length(trim(full_name)) <= 100),

  phone varchar(15)
    constraint profiles_phone_format_check
      check (phone is null or (
          char_length(trim(phone)) between 7 and 14
      and trim(phone) ~ '^\+?[0-9]+$'
    )),
  email              varchar(254)
    constraint profiles_email_len_check
      check (email is null or char_length(trim(email)) <= 254),

  avatar_url         varchar(2048)
    constraint profiles_avatar_url_len_check
      check (avatar_url is null or char_length(avatar_url) <= 2048),

  is_staff           boolean not null default false,
  is_admin           boolean not null default false,
  is_manager         boolean not null default false,
  is_library_staff   boolean not null default false,
  is_developer      boolean not null default false,

  is_verified        boolean not null default false,
  is_active          boolean not null default true,

  profile_extras     jsonb not null default '{}'::jsonb
    constraint profiles_profile_extras_size_check
      check (octet_length(profile_extras::text) <= 24576),

  admin_note_cipher  bytea
    constraint profiles_admin_note_cipher_size_check
      check (admin_note_cipher is null or octet_length(admin_note_cipher) <= 32768),

  deleted_at         timestamptz,
  deleted_by         uuid references auth.users (id) on delete set null,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),

  constraint profiles_external_member_no_positive check (external_member_no is null or external_member_no > 0)
);

create unique index profiles_external_member_no_key
  on public.profiles (external_member_no);
create index profiles_email_lower_idx on public.profiles (lower(email));
create index profiles_active_idx on public.profiles (user_id) where deleted_at is null;

-- ---------------------------------------------------------------------------
-- verification
-- ---------------------------------------------------------------------------
create table public.verification (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid not null references auth.users (id) on delete cascade,

  status             varchar(32) not null default 'pending'
    constraint verification_status_allowed_check
      check (lower(status) in ('pending', 'approved', 'rejected', 'resubmit')),

  submitted_at       timestamptz not null default now(),
  reviewed_at        timestamptz,
  reviewed_by        uuid references auth.users (id) on delete set null,

  student_message    varchar(2000)
    constraint verification_student_message_len_check
      check (student_message is null or char_length(student_message) <= 2000),

  reviewer_message   varchar(2000)
    constraint verification_reviewer_message_len_check
      check (reviewer_message is null or char_length(reviewer_message) <= 2000),

  internal_note_cipher bytea
    constraint verification_internal_note_cipher_size_check
      check (internal_note_cipher is null or octet_length(internal_note_cipher) <= 32768),

  resubmit_count     integer not null default 0
    constraint verification_resubmit_count_bounds check (resubmit_count >= 0 and resubmit_count <= 100),

  deleted_at         timestamptz,
  deleted_by         uuid references auth.users (id) on delete set null,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index verification_user_idx on public.verification (user_id);
create unique index verification_one_pending_per_user_idx
  on public.verification (user_id)
  where lower(status) = 'pending' and deleted_at is null;

-- ---------------------------------------------------------------------------
-- verification_documents
-- ---------------------------------------------------------------------------
create table public.verification_documents (
  id                uuid primary key default gen_random_uuid(),
  verification_id   uuid not null references public.verification (id) on delete cascade,
  user_id           uuid not null references auth.users (id) on delete cascade,

  doc_type          varchar(64) not null
    constraint verification_documents_doc_type_len_check
      check (char_length(trim(doc_type)) >= 1 and char_length(doc_type) <= 64),

  phase             varchar(32) not null default 'submitted'
    constraint verification_documents_phase_allowed_check
      check (lower(phase) in ('checkout_pending', 'submitted', 'superseded')),

  storage_bucket    varchar(128) not null
    constraint verification_documents_bucket_len_check
      check (char_length(storage_bucket) <= 128),
  storage_path      varchar(1024) not null
    constraint verification_documents_path_len_check
      check (char_length(storage_path) <= 1024),

  content_type      varchar(128) not null
    constraint verification_documents_content_type_len_check
      check (char_length(content_type) <= 128),

  byte_size         bigint
    constraint verification_documents_byte_size_check
      check (byte_size is null or (byte_size >= 0 and byte_size <= 52428800)),

  checksum_sha256   varchar(128)
    constraint verification_documents_checksum_len_check
      check (checksum_sha256 is null or char_length(checksum_sha256) <= 128),

  deleted_at        timestamptz,
  deleted_by        uuid references auth.users (id) on delete set null,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index verification_documents_verification_idx on public.verification_documents (verification_id);
create unique index verification_documents_one_per_slot_idx
  on public.verification_documents (verification_id, doc_type, phase)
  where deleted_at is null;

-- ---------------------------------------------------------------------------
-- memberships
-- ---------------------------------------------------------------------------
create table public.memberships (
  id               uuid primary key default gen_random_uuid(),
  user_id          uuid not null references auth.users (id) on delete cascade,

  plan_code        varchar(80) not null
    constraint memberships_plan_code_len_check
      check (char_length(trim(plan_code)) >= 1 and char_length(plan_code) <= 80),

  status           varchar(32) not null default 'pending_payment'
    constraint memberships_status_allowed_check
      check (
        lower(status) in ('pending_payment', 'active', 'expired', 'cancelled', 'paused')
      ),

  quantity         integer not null default 1
    constraint memberships_quantity_bounds check (quantity > 0 and quantity <= 1000),

  currency         varchar(3) not null default 'USD'
    constraint memberships_currency_len_check
      check (char_length(trim(currency)) >= 3 and char_length(currency) <= 3),

  unit_amount_cents bigint
    constraint memberships_unit_amount_cents_bounds
      check (unit_amount_cents is null or (unit_amount_cents >= 0 and unit_amount_cents <= 2147483647)),

  starts_at        timestamptz,
  ends_at          timestamptz,
  valid_from       date,
  valid_until      date,

  seat_label       varchar(64)
    constraint memberships_seat_label_len_check
      check (seat_label is null or char_length(seat_label) <= 64),

  metadata         jsonb not null default '{}'::jsonb
    constraint memberships_metadata_size_check
      check (octet_length(metadata::text) <= 24576),

  notes            varchar(4000)
    constraint memberships_notes_len_check
      check (notes is null or char_length(notes) <= 4000),

  payment_id       uuid,

  deleted_at       timestamptz,
  deleted_by       uuid references auth.users (id) on delete set null,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create index memberships_user_idx on public.memberships (user_id);
create index memberships_user_status_idx on public.memberships (user_id, status) where deleted_at is null;
create index memberships_payment_idx on public.memberships (payment_id);

-- ---------------------------------------------------------------------------
-- payments
-- ---------------------------------------------------------------------------
create table public.payments (
  id                   uuid primary key default gen_random_uuid(),
  user_id              uuid not null references auth.users (id) on delete cascade,
  membership_id        uuid references public.memberships (id) on delete set null,

  amount_cents         bigint not null
    constraint payments_amount_cents_bounds
      check (amount_cents >= 0 and amount_cents <= 999999999999),

  currency             varchar(3) not null default 'USD'
    constraint payments_currency_len_check
      check (char_length(trim(currency)) = 3),

  provider             varchar(64)
    constraint payments_provider_len_check
      check (provider is null or char_length(provider) <= 64),

  provider_payment_id   varchar(255)
    constraint payments_provider_payment_id_len_check
      check (provider_payment_id is null or char_length(provider_payment_id) <= 255),

  provider_order_id    varchar(255)
    constraint payments_provider_order_id_len_check
      check (provider_order_id is null or char_length(provider_order_id) <= 255),

  status               varchar(32) not null default 'pending'
    constraint payments_status_allowed_check
      check (
        lower(status) in (
          'pending', 'paid', 'failed', 'refunded', 'partially_refunded'
        )
      ),

  idempotency_key       varchar(128)
    constraint payments_idempotency_key_len_check
      check (idempotency_key is null or char_length(idempotency_key) <= 128),

  metadata              jsonb not null default '{}'::jsonb
    constraint payments_metadata_size_check
      check (octet_length(metadata::text) <= 32768),

  deleted_at           timestamptz,
  deleted_by           uuid references auth.users (id) on delete set null,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

create index payments_user_idx on public.payments (user_id);
create index payments_membership_idx on public.payments (membership_id);
create unique index payments_idempotency_pending_idx
  on public.payments (idempotency_key)
  where idempotency_key is not null and lower(status) = 'pending' and deleted_at is null;

create unique index payments_provider_payment_unique_idx
  on public.payments (provider, provider_payment_id)
  where provider is not null and provider_payment_id is not null and deleted_at is null;

alter table public.memberships
  add constraint memberships_payment_id_fkey
  foreign key (payment_id) references public.payments (id) on delete set null;

-- ---------------------------------------------------------------------------
-- testimonials
-- ---------------------------------------------------------------------------
create table public.testimonials (
  id                uuid primary key default gen_random_uuid(),

  user_id           uuid references auth.users (id) on delete set null,

  author_name       varchar(100) not null
    constraint testimonials_author_name_len_check
      check (char_length(trim(author_name)) >= 2 and char_length(author_name) <= 100),

  author_title      varchar(160)
    constraint testimonials_author_title_len_check
      check (author_title is null or char_length(author_title) <= 160),

  author_company    varchar(160)
    constraint testimonials_author_company_len_check
      check (author_company is null or char_length(author_company) <= 160),

  author_avatar_url varchar(2048)
    constraint testimonials_author_avatar_url_len_check
      check (author_avatar_url is null or char_length(author_avatar_url) <= 2048),

  rating            smallint
    constraint testimonials_rating_range check (rating is null or (rating between 1 and 5)),

  title             varchar(200)
    constraint testimonials_title_len_check
      check (title is null or char_length(title) <= 200),

  body              varchar(8000) not null
    constraint testimonials_body_len_check
      check (char_length(trim(body)) >= 10 and char_length(body) <= 8000),

  locale            varchar(16) not null default 'en'
    constraint testimonials_locale_len_check
      check (char_length(locale) >= 2 and char_length(locale) <= 16),

  is_featured       boolean not null default false,
  sort_order        integer not null default 0
    constraint testimonials_sort_order_bounds check (sort_order >= -100000 and sort_order <= 100000),

  status            varchar(32) not null default 'pending'
    constraint testimonials_status_allowed_check
      check (lower(status) in ('pending', 'approved', 'rejected', 'archived')),

  published_at      timestamptz,
  moderated_by      uuid references auth.users (id) on delete set null,
  moderated_at      timestamptz,

  reject_reason     varchar(500)
    constraint testimonials_reject_reason_len_check
      check (reject_reason is null or char_length(reject_reason) <= 500),

  source            varchar(120)
    constraint testimonials_source_len_check
      check (source is null or char_length(source) <= 120),

  ip_hash           varchar(128)
    constraint testimonials_ip_hash_len_check
      check (ip_hash is null or char_length(ip_hash) <= 128),

  deleted_at        timestamptz,
  deleted_by        uuid references auth.users (id) on delete set null,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index testimonials_list_idx
  on public.testimonials (status, is_featured, sort_order, published_at desc)
  where deleted_at is null;

-- ---------------------------------------------------------------------------
-- updated_at triggers
-- ---------------------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger trg_profiles_updated before update on public.profiles
  for each row execute function public.touch_updated_at();
create trigger trg_verification_updated before update on public.verification
  for each row execute function public.touch_updated_at();
create trigger trg_verification_documents_updated before update on public.verification_documents
  for each row execute function public.touch_updated_at();
create trigger trg_memberships_updated before update on public.memberships
  for each row execute function public.touch_updated_at();
create trigger trg_payments_updated before update on public.payments
  for each row execute function public.touch_updated_at();
create trigger trg_testimonials_updated before update on public.testimonials
  for each row execute function public.touch_updated_at();

commit;
