-- Single-use discount coupons generated by library admins.
-- Code format: MANI + 4 hex chars (8 chars total), e.g. MANI0000, MANIFF1B.
-- Each coupon applies to ONE plan (library_plans.code) and is redeemable once.

create table if not exists public.library_coupons (
  id               uuid primary key default gen_random_uuid(),
  code             text not null unique
    constraint library_coupons_code_format_check check (code ~ '^MANI[0-9A-F]{4}$'),
  discount_percent smallint not null
    constraint library_coupons_discount_range_check check (discount_percent between 10 and 90),
  plan_code        text not null references public.library_plans (code) on delete cascade,
  status           text not null default 'active'
    constraint library_coupons_status_check check (status in ('active', 'used')),
  used_at          timestamptz,
  used_by_user_id  uuid,
  membership_id    uuid,
  created_by       uuid,
  created_at       timestamptz not null default now()
);

create index if not exists library_coupons_status_created_idx
  on public.library_coupons (status, created_at desc);

alter table public.library_coupons enable row level security;

do $$
begin
  if exists (
    select 1 from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.proname = 'is_library_admin'
  ) then
    drop policy if exists library_coupons_admin on public.library_coupons;
    create policy library_coupons_admin on public.library_coupons
      for all to authenticated
      using (public.is_library_admin() or public.is_library_superadmin())
      with check (public.is_library_admin() or public.is_library_superadmin());
  end if;
end $$;
